### ISSUE TITLE
support lists configuration yml 

### ISSUE THREAD

**Issue by georg-e** [BelWue/flowpipeline#16]
enable lists inside of segments in configuration.
e.g.
```yml
- segment: example
  config:
    list:
      - val1
      - val2
```

This should be extended by modifing https://github.com/bwNetFlow/flowpipeline/blob/master/pipeline/config.go
